import math
import re
import time
import traceback
from typing import Any

import numpy as np
from llamea import Solution

from evolution.domain.entities import ExperimentSummary
from evolution.domain.interfaces import BaseProblem
from evolution.domain.vos import (
    Code,
    Convergence,
    Error,
    Execution,
    Fitness,
    IterationMetadata,
    ProblemProfile,
)
from shared.execution import AlgorithmExecutor, AlgorithmTimeoutException
from evolution.infra.logging import SynthesisLogger
from evolution.infra.storage.base import SynthesisRepository
from evolution.infra.storage.code.repository import CodeRepository


_DIVERSITY_INJECTION_MSG = (
    "\n\n[META-FEEDBACK] Your last {n} algorithms all failed to execute correctly on "
    "this noisy optimization problem. You MUST try a completely different algorithm "
    "family — do NOT generate another DE or GA variant. Consider: Particle Swarm "
    "Optimization (PSO), Simulated Annealing, CMA-style covariance updates, "
    "or a hill-climber with noise-averaged comparisons. The root issue is that your "
    "algorithm is not accounting for the stochastic nature of the objective function."
)


class Evaluator:
    """
    LLaMEA-compatible evaluator for BBOB optimization problems under noise.

    Workflow:
                 solution.code (generated by LLM)
                                │
                                ▼
                  AlgorithmExecutor.execute_algorithm()
                                │
           ┌────────────────────┴────────────────────────────────────────┐
        Success                                                       Failure
    (returns best_x, raw_y)                               (Timeout, Runtime, Syntax)
           │                                                             │
           ▼                                                             ▼
    1. Validate bounds & dim                             1. Classify failure tier:
    2. Re-evaluate clean optimum:                           • Timeout:  -5e8
       y_clean = problem.eval_clean(best_x)                 • Runtime:  -7e8
       error = |y_clean - y*|                               • Syntax:   -1e9
    3. Fitness score = -error                            2. Extract traceback code snippet
    4. Reset consecutive failures                        3. Increment consecutive failures
           │                                                             │
           └────────────────────────────┬────────────────────────────────┘
                                        ▼
                         Stagnation Detection Check:
                 If consecutive_failures >= threshold (3):
                 Inject [META-FEEDBACK] (Force PSO/CMA-ES paradigm shift)
                                        │
                                        ▼
                         solution.set_scores(fitness, feedback)
                                        │
                                        ▼
                         Dual Repository Persistence:
                         • Save source code -> CodeRepository
                         • Append telemetry -> SynthesisRepository
                                        │
                                        ▼
                                 Return solution
    """

    FAILURE_FITNESS: float = -1e9
    RUNTIME_FAILURE_FITNESS: float = -7e8
    TIMEOUT_FAILURE_FITNESS: float = -5e8

    @classmethod
    def is_failure(cls, score: float) -> bool:
        """Returns True if the score represents any failure tier (crash, runtime, or timeout)."""
        return not math.isfinite(score) or score <= -4e8

    def __init__(
        self,
        problem: BaseProblem,
        db_repo: SynthesisRepository,
        code_repo: CodeRepository,
        budget: int = 1000000,
        timeout_seconds: float = 10.0,
        experiment_id: int = 1,
        initial_iteration: int = 0,
        convergence_threshold: float = 1e-6,
        stagnation_threshold: int = 3,
        logger: SynthesisLogger | None = None,
        experiment: ExperimentSummary | None = None,
    ) -> None:
        """Initialize the evaluator.

        Args:
            problem: Fully-configured optimization problem instance implementing BaseProblem interface.
            db_repo: ExperimentRepository to persist incremental iteration records.
            code_repo: CodeRepository to persist algorithm source code per iteration.
            budget: Maximum allowed objective function evaluations passed to the algorithm
                as a stopping criterion (analogous to a convergence threshold in gradient
                descent), by default 1000. It is NOT used for multi-run comparison or luck checking.
            timeout_seconds: Maximum wall-clock execution time allowed for one algorithm run,
                by default 10.0.
            experiment_id: Globally unique experiment primary key, by default 1.
            initial_iteration: Starting iteration counter (e.g. from warm start), by default 0.
            convergence_threshold: Target error threshold required to consider a run converged, by default 1e-6.
            stagnation_threshold: Number of consecutive failure iterations before triggering diversity injection, by default 3.
            logger: SynthesisLogger instance for console output.
            experiment: Optional live ExperimentSummary domain aggregate to update with iteration champions.
        """
        self._problem = problem
        self._db_repo = db_repo
        self._code_repo = code_repo
        self._budget = budget
        self._timeout_seconds = timeout_seconds
        self._experiment_id = experiment_id
        self._executor = AlgorithmExecutor(timeout_seconds=self._timeout_seconds)
        self._current_iteration = initial_iteration
        self._convergence_threshold = convergence_threshold
        self._stagnation_threshold = stagnation_threshold
        self._consecutive_failures = 0
        self._logger = logger or SynthesisLogger()
        self._experiment = experiment

    @property
    def experiment(self) -> ExperimentSummary | None:
        """Expose the associated live ExperimentSummary entity."""
        return self._experiment

    @experiment.setter
    def experiment(self, value: ExperimentSummary | None) -> None:
        self._experiment = value

    @property
    def problem_profile(self) -> ProblemProfile:
        """Expose the configured BBOB problem profile."""
        return ProblemProfile(
            problem_id=self._problem.problem_id,
            dim=self._problem.dim,
            noise_std=self._problem.noise_std,
            noise_model=self._problem.noise_model,
            instance_id=self._problem.instance_id,
            true_optimum=self._problem.true_optimum,
        )

    def _resolve_clean_objective(
        self,
        best_x: np.ndarray | None,
        algorithm_returned_fitness: float,
    ) -> float:
        """Validate best_x dimension/bounds if present, re-evaluate clean objective value, and check finite return."""
        if best_x is not None:
            if len(best_x) != self._problem.dim:
                raise ValueError(
                    f"Returned best_x has dimension {len(best_x)}, expected problem dimension {self._problem.dim}."
                )
            if not self._problem.is_in_bounds(best_x):
                lb_val, ub_val = self._problem.lower_bound[0], self._problem.upper_bound[0]
                raise ValueError(
                    f"Returned best_x {best_x.tolist()} is outside search space bounds [{lb_val}, {ub_val}]. "
                    "Ensure your algorithm clips candidate solutions to domain bounds using problem.clip(x) or np.clip(x, lb, ub)."
                )
            clean_y = self._problem.eval_clean(best_x)
        else:
            clean_y = algorithm_returned_fitness

        if not math.isfinite(clean_y):
            raise ValueError(
                f"[INVALID RETURN] Algorithm returned a non-finite value ({clean_y}). "
                "Ensure __call__ returns a valid float — no NaN or inf."
            )

        return clean_y

    def _extract_code_context_from_traceback(self, tb_str: str, candidate_code: str) -> str:
        """Extract lines of generated candidate code referenced in the exception traceback."""
        if not candidate_code or not tb_str:
            return ""

        code_lines = candidate_code.splitlines()
        matches = re.findall(r'File "<string>", line (\d+)', tb_str) or re.findall(
            r'File "[^"]*<string>[^"]*", line (\d+)', tb_str
        )
        if not matches:
            return ""

        context_blocks = []
        seen_lines: set[int] = set()
        for line_str in matches:
            line_num = int(line_str)
            if line_num in seen_lines:
                continue
            seen_lines.add(line_num)

            idx = line_num - 1
            if 0 <= idx < len(code_lines):
                start = max(0, idx - 2)
                end = min(len(code_lines), idx + 3)
                snippet_lines = []
                for i in range(start, end):
                    prefix = "->" if i == idx else "  "
                    snippet_lines.append(f"  {prefix} line {i + 1:3d}: {code_lines[i]}")
                context_blocks.append("\n".join(snippet_lines))

        if not context_blocks:
            return ""

        return "\nRelevant code lines from your algorithm:\n" + "\n---\n".join(context_blocks)

    def _build_success_feedback(
        self,
        final_error: float,
        true_optimum: float,
        captured_warnings: list[str] | None = None,
    ) -> str:
        """Build feedback string for a successful algorithm run."""
        noise_desc = (
            f" (noise model: {self._problem.noise_model})" if self._problem.noise_std > 0 else ""
        )
        msg = (
            f"The algorithm achieved a final clean error of {final_error:.4f} from the true optimum ({true_optimum:.4f}) "
            f"on BBOB Problem {self._problem.problem_id}{noise_desc}. "
            "Improve convergence speed and resilience to minimize the final error."
        )
        if self._problem.noise_std > 0 and final_error > self._convergence_threshold * 100:
            msg += (
                "\n\n[NOISY PROBLEM] Your algorithm returned a large error on a noisy objective function. "
                "This typically happens when selection decisions are made from a single noisy observation. "
                "Use re-evaluation: call problem(x) multiple times per candidate and compare means/medians "
                "instead of raw values. Budget re-evaluations to stay within 20% of your total budget."
            )
        if captured_warnings:
            warn_str = "\n".join(f"  - {w}" for w in captured_warnings)
            msg += (
                f"\n\nNumPy/Runtime Warnings raised during execution (these may indicate silent bugs):\n"
                f"{warn_str}\n"
                "Check that your code never passes negative values to sqrt, log, or similar functions."
            )
        return msg

    def _build_success_metadata(
        self,
        algorithm_name: str,
        algorithm_returned_fitness: float,
        final_error: float,
        runtime_seconds: float,
        evaluations_used: int,
        code_lines: int,
        code_length: int,
        llm_generation_time: float | None = None,
    ) -> IterationMetadata:
        """Construct IterationMetadata object for successful algorithm executions."""
        true_optimum = self._problem.true_optimum
        budget_consumed_pct = (evaluations_used / self._budget * 100) if self._budget > 0 else 0.0
        relative_error = (final_error / abs(true_optimum)) if true_optimum != 0.0 else final_error
        evals_per_second = (evaluations_used / runtime_seconds) if runtime_seconds > 0.0 else 0.0
        error_per_evaluation = (final_error / evaluations_used) if evaluations_used > 0 else None

        return IterationMetadata(
            algorithm_name=algorithm_name,
            execution=Execution(
                timed_out=False,
                runtime_seconds=runtime_seconds,
                llm_generation_time=llm_generation_time,
                evaluations_used=evaluations_used,
                budget_consumed_pct=budget_consumed_pct,
                evals_per_second=evals_per_second,
            ),
            fitness=Fitness(
                raw_fitness=algorithm_returned_fitness,
                final_error=final_error,
                relative_error=relative_error,
                error_per_evaluation=error_per_evaluation,
            ),
            code=Code(
                code_lines=code_lines,
                code_length=code_length,
                code_path=None,
            ),
            error=Error(
                error_type=None,
                error_message=None,
                error_traceback=None,
            ),
            convergence=Convergence.evaluate(final_error, self._convergence_threshold),
        )

    def _calculate_fitness_and_feedback(
        self,
        algorithm_returned_fitness: float,
        best_x: np.ndarray | None,
        algorithm_name: str,
        runtime_seconds: float,
        evaluations_used: int,
        code_lines: int,
        code_length: int,
        llm_generation_time: float | None = None,
        captured_warnings: list[str] | None = None,
    ) -> tuple[float, str, IterationMetadata]:
        """
        Compute final error, fitness score, feedback message, and metadata object.
        Re-evaluates best_x on the clean underlying problem to calculate an unbiased final error.
        """
        true_optimum = self._problem.true_optimum
        clean_y = self._resolve_clean_objective(best_x, algorithm_returned_fitness)
        final_error = abs(clean_y - true_optimum)

        feedback = self._build_success_feedback(
            final_error, true_optimum, captured_warnings=captured_warnings
        )
        metadata = self._build_success_metadata(
            algorithm_name=algorithm_name,
            algorithm_returned_fitness=algorithm_returned_fitness,
            final_error=final_error,
            runtime_seconds=runtime_seconds,
            evaluations_used=evaluations_used,
            code_lines=code_lines,
            code_length=code_length,
            llm_generation_time=llm_generation_time,
        )

        # LLaMEA expects a fitness score where higher is better.
        # We negate the final_error so that an error of 0 is the max (0.0), and larger errors are more negative.
        fitness_score = -final_error

        self._logger.generation(
            gen_idx=self._current_iteration + 1,
            total_gens=10,
            algo_name=algorithm_name or "Candidate",
            error=final_error,
            fitness=fitness_score,
            evals_used=evaluations_used,
            runtime=runtime_seconds,
            is_failure=False,
        )

        return fitness_score, feedback, metadata

    def _run_and_score_algorithm(
        self,
        solution: Solution,
        start_time: float,
        code_lines: int,
        code_length: int,
        llm_gen_time: float | None,
    ) -> tuple[float, str, IterationMetadata]:
        """Compile, execute algorithm run with exception handling, and return metrics/feedback."""
        problem_fn = self._problem.get_objective_fn()
        try:
            best_x, algorithm_returned_fitness = self._executor.execute_algorithm(
                code=solution.code,
                name=solution.name,
                dim=self._problem.dim,
                problem=problem_fn,
                budget=self._budget,
            )
            elapsed_time = time.perf_counter() - start_time
            evals_used = self._problem.evaluations
            captured = getattr(self._executor, "last_captured_warnings", [])

            return self._calculate_fitness_and_feedback(
                algorithm_returned_fitness,
                best_x,
                solution.name,
                elapsed_time,
                evals_used,
                code_lines,
                code_length,
                llm_generation_time=llm_gen_time,
                captured_warnings=captured,
            )
        except Exception as error:
            captured = getattr(self._executor, "last_captured_warnings", [])
            return self._score_failed_algorithm(
                error,
                solution.name,
                start_time,
                code_lines,
                code_length,
                llm_gen_time,
                candidate_code=solution.code,
                captured_warnings=captured,
            )

    def _generate_error_feedback(
        self,
        error: Exception,
        is_timeout: bool,
        candidate_code: str = "",
        captured_warnings: list[str] | None = None,
    ) -> str:
        """Generate categorized feedback message based on exception type."""
        if is_timeout:
            msg = (
                f"[TIMEOUT] Execution failed: Your algorithm exceeded the {self._timeout_seconds}-second time limit. "
                "Please optimize your loops and make the code more efficient."
            )
        elif isinstance(error, (SyntaxError, IndentationError)):
            msg = (
                f"[SYNTAX ERROR] The generated code has a Python syntax error:\n"
                f"{traceback.format_exc()}\n"
                "Please fix the syntax error."
            )
        elif isinstance(error, (ZeroDivisionError, OverflowError)):
            msg = (
                f"[MATH ERROR] Execution failed with math exception ({type(error).__name__}): {error}.\n"
                f"{traceback.format_exc()}\n"
                "Please add mathematical guards (e.g. avoid dividing by zero or overflow)."
            )
        elif isinstance(error, (ValueError, TypeError)):
            msg = (
                f"[RUNTIME ERROR] Execution failed with {type(error).__name__}: {error}.\n"
                f"{traceback.format_exc()}\n"
                "Please check array shapes, types, and return values."
            )
        else:
            msg = (
                f"[RUNTIME ERROR] Execution failed with the following Python error:\n"
                f"{traceback.format_exc()}\n"
                "Please fix the bugs."
            )

        # Option A: Extract traceback code context if available
        tb_str = traceback.format_exc() if not is_timeout else ""
        code_context = self._extract_code_context_from_traceback(tb_str, candidate_code)
        if code_context:
            msg += f"\n{code_context}"

        # Option D: Append captured warnings if any
        if captured_warnings:
            warn_str = "\n".join(f"  - {w}" for w in captured_warnings)
            msg += (
                f"\n\nNumPy/Runtime Warnings raised during execution (these may indicate silent bugs):\n"
                f"{warn_str}\n"
                "Check that your code never passes negative values to sqrt, log, or similar functions."
            )

        # Option B: Append problem context footer
        lb_val = self._problem.lower_bound[0] if hasattr(self._problem, "lower_bound") else -5.0
        ub_val = self._problem.upper_bound[0] if hasattr(self._problem, "upper_bound") else 5.0
        msg += (
            f"\n\nProblem context: BBOB-{self._problem.problem_id}, dim={self._problem.dim}, bounds=[{lb_val}, {ub_val}]. "
            f"Ensure your algorithm handles small dimensionality (dim={self._problem.dim}) correctly, "
            "especially matrix operations (e.g. covariance matrices, eigenvectors) that may degenerate when dim is 1, 2, or 3."
        )

        if self._problem.noise_std > 0:
            msg += (
                "\n\n[NOISY PROBLEM CONTEXT] This is a stochastic objective — common causes of failure:\n"
                "1. Corrupted best_y: storing a smoothed/mixed value as best_y (e.g. 0.9*best_y + 0.1*trial_y) "
                "returns an invalid objective value. Always store raw evaluations, never smoothed.\n"
                "2. Hidden budget exhaustion: problem(x) calls inside min(key=...) or list comprehensions "
                "are not tracked by your evaluations counter. Count every call explicitly.\n"
                "3. Misplaced counter: evaluations += 1 must be directly after every problem(x) call, "
                "not once per outer loop iteration."
            )

        return msg

    def _score_failed_algorithm(
        self,
        error: Exception,
        solution_name: str,
        start_time: float,
        code_lines: int,
        code_length: int,
        llm_gen_time: float | None,
        candidate_code: str = "",
        captured_warnings: list[str] | None = None,
    ) -> tuple[float, str, IterationMetadata]:
        """Handle execution timeout or runtime error, generating failure feedback and metadata."""
        elapsed_time = time.perf_counter() - start_time
        evals_used = self._problem.evaluations
        is_timeout = isinstance(error, AlgorithmTimeoutException)

        if is_timeout:
            internal_score = self.TIMEOUT_FAILURE_FITNESS
        elif isinstance(
            error,
            (ValueError, TypeError, ZeroDivisionError, OverflowError, FloatingPointError),
        ):
            internal_score = self.RUNTIME_FAILURE_FITNESS
        else:
            internal_score = self.FAILURE_FITNESS

        feedback = self._generate_error_feedback(
            error=error,
            is_timeout=is_timeout,
            candidate_code=candidate_code,
            captured_warnings=captured_warnings,
        )

        metadata = self._build_failure_metadata(
            error=error,
            solution_name=solution_name,
            elapsed_time=elapsed_time,
            evals_used=evals_used,
            code_lines=code_lines,
            code_length=code_length,
            llm_gen_time=llm_gen_time,
            is_timeout=is_timeout,
        )

        self._logger.generation(
            gen_idx=self._current_iteration + 1,
            total_gens=10,
            algo_name=solution_name or "Candidate",
            error=None,
            fitness=None,
            evals_used=evals_used,
            runtime=elapsed_time,
            is_failure=True,
            failure_reason=type(error).__name__,
        )

        return internal_score, feedback, metadata

    def _build_failure_metadata(
        self,
        error: Exception,
        solution_name: str,
        elapsed_time: float,
        evals_used: int,
        code_lines: int,
        code_length: int,
        llm_gen_time: float | None,
        is_timeout: bool,
    ) -> IterationMetadata:
        """Construct IterationMetadata for a failed run."""
        error_traceback = None if is_timeout else traceback.format_exc()
        budget_consumed_pct = (evals_used / self._budget * 100) if self._budget > 0 else 0.0
        evals_per_second = (evals_used / elapsed_time) if elapsed_time > 0.0 else 0.0

        return IterationMetadata(
            algorithm_name=solution_name,
            execution=Execution(
                timed_out=is_timeout,
                runtime_seconds=elapsed_time,
                llm_generation_time=llm_gen_time,
                evaluations_used=evals_used,
                budget_consumed_pct=budget_consumed_pct,
                evals_per_second=evals_per_second,
            ),
            fitness=Fitness(
                raw_fitness=None,
                final_error=None,
                relative_error=None,
                error_per_evaluation=None,
            ),
            code=Code(
                code_lines=code_lines,
                code_length=code_length,
                code_path=None,
            ),
            error=Error(
                error_type=type(error).__name__,
                error_message=str(error),
                error_traceback=error_traceback,
            ),
            convergence=Convergence.evaluate(None, self._convergence_threshold),
        )

    def _persist_iteration(self, solution: Solution, metadata: IterationMetadata) -> None:
        """Record iteration count, save code file, and persist metadata to database repo."""
        self._current_iteration += 1
        code_path_str: str | None = None

        # 1. Save candidate code file immediately
        if solution.code:
            code_path = self._code_repo.save_code(
                code=solution.code,
                iteration_num=self._current_iteration,
                experiment_id=self._experiment_id,
            )
            code_path_str = str(code_path)

        # Re-create updated, immutable metadata using model_copy
        updated_code = metadata.code.model_copy(update={"code_path": code_path_str})
        final_metadata = metadata.model_copy(
            update={
                "iteration": self._current_iteration,
                "code": updated_code,
            }
        )

        # 2. Append complete iteration metadata to database repo
        self._db_repo.append_iteration(
            experiment_id=self._experiment_id,
            metadata=final_metadata,
        )

        # 3. Update in-memory domain aggregate
        if self._experiment is not None:
            self._experiment.record_iteration(final_metadata, self._current_iteration)

    def __call__(self, solution: Solution, explogger: Any | None = None) -> Solution:
        """Execute and score a candidate optimization algorithm solution.

        Args:
            solution: The LLaMEA candidate solution containing its source code and name.
            explogger: Framework-level experiment logger, by default None.

        Returns:
            Solution: The modified solution object populated with fitness scores and feedback.
        """
        code_lines = len(solution.code.splitlines())
        code_length = len(solution.code)
        llm_gen_time = solution.metadata.get("llm_generation_time")

        self._problem.reset()
        start_time = time.perf_counter()

        fitness_score, feedback, metadata = self._run_and_score_algorithm(
            solution, start_time, code_lines, code_length, llm_gen_time
        )

        if not math.isfinite(fitness_score):
            fitness_score = self.FAILURE_FITNESS

        if self.is_failure(fitness_score):
            self._consecutive_failures += 1
        else:
            self._consecutive_failures = 0

        diversity_text = ""
        if self._consecutive_failures >= self._stagnation_threshold:
            self._logger.stagnation_warning(self._consecutive_failures, self._stagnation_threshold)
            diversity_text = _DIVERSITY_INJECTION_MSG.format(n=self._stagnation_threshold)
            self._consecutive_failures = 0

        final_feedback = feedback + diversity_text
        solution.set_scores(fitness_score, final_feedback)
        self._persist_iteration(solution, metadata)

        return solution

    def __getstate__(self) -> dict[str, Any]:
        # Exclude unpicklable C++ executor wrapper and logger stream handlers.
        state = self.__dict__.copy()
        state["_executor"] = None
        state["_logger"] = None
        return state

    def __setstate__(self, state: dict[str, Any]) -> None:
        self.__dict__.update(state)
        # Re-initialize the executor and logger on resume.
        self._executor = AlgorithmExecutor(timeout_seconds=self._timeout_seconds)
        self._logger = getattr(self, "_logger", None) or SynthesisLogger()
        if self._db_repo is None:
            print(
                "[WARN] Evaluator resumed from pickle with _db_repo=None. "
                "Iteration persistence is DISABLED for this run. "
                "Call evaluator._db_repo = repo to re-attach."
            )
        if self._code_repo is None:
            print(
                "[WARN] Evaluator resumed from pickle with _code_repo=None. "
                "Code file saving is DISABLED for this run."
            )
