import time
import traceback
from typing import Any

import numpy as np
from llamea import Solution

from domain.interfaces import BaseProblem
from domain.vos import (
    Code,
    Convergence,
    Error,
    Execution,
    Fitness,
    IterationMetadata,
    ProblemProfile,
)
from synthesis.execution.exceptions import AlgorithmTimeoutException
from synthesis.execution import AlgorithmExecutor
from infra.storage.base import ExperimentRepository
from infra.storage.code.repository import CodeRepository


class Evaluator:
    """
    LLaMEA-compatible evaluator for BBOB optimization problems.

    Workflow:
                 solution.code (generated by LLM)
                                │
                                ▼
                  AlgorithmExecutor.execute_algorithm()
                                │
           ┌────────────────────┴────────────────────┐
        Success                                   Failure
    (returns fitness)                   (Validation, Runtime, Timeout)
           │                                         │
           ▼                                         ▼
    Calculate metrics                       Capture traceback / error
    (final error, runtime, evals)           Build failure feedback string
           │                                         │
           └────────────────────┬────────────────────┘
                                ▼
                  solution.set_scores(fitness, feedback)
                  Save code & IterationMetadata to DB
                                │
                                ▼
                         Return solution
    """

    def __init__(
        self,
        problem: BaseProblem,
        db_repo: ExperimentRepository,
        code_repo: CodeRepository,
        budget: int = 1000,
        timeout_seconds: float = 10.0,
        experiment_id: int = 1,
        initial_iteration: int = 0,
        convergence_threshold: float = 1e-6,
    ) -> None:
        """Initialize the evaluator.

        Args:
            problem: Fully-configured optimization problem instance implementing BaseProblem interface.
            db_repo: ExperimentRepository to persist incremental iteration records.
            code_repo: CodeRepository to persist algorithm source code per iteration.
            budget: Maximum allowed objective function evaluations passed to the algorithm
                as a stopping criterion (analogous to a convergence threshold in gradient
                descent), by default 1000. It is NOT used for multi-run comparison or luck checking.
            timeout_seconds: Maximum wall-clock execution time allowed for one algorithm run,
                by default 10.0.
            experiment_id: Globally unique experiment primary key, by default 1.
            initial_iteration: Starting iteration counter (e.g. from warm start), by default 0.
            convergence_threshold: Target error threshold required to consider a run converged, by default 1e-6.
        """
        self._problem = problem
        self._db_repo = db_repo
        self._code_repo = code_repo
        self._budget = budget
        self._timeout_seconds = timeout_seconds
        self._experiment_id = experiment_id
        self._executor = AlgorithmExecutor(timeout_seconds=self._timeout_seconds)
        self._current_iteration = initial_iteration
        self._convergence_threshold = convergence_threshold

    @property
    def problem_profile(self) -> ProblemProfile:
        """Expose the configured BBOB problem profile."""
        return ProblemProfile(
            problem_id=self._problem.problem_id,
            dim=self._problem.dim,
            noise_std=self._problem.noise_std,
            noise_model=self._problem.noise_model,
            instance_id=self._problem.instance_id,
            true_optimum=self._problem.true_optimum,
        )

    def _calculate_fitness_and_feedback(
        self,
        algorithm_returned_fitness: float,
        best_x: np.ndarray | None,
        algorithm_name: str,
        runtime_seconds: float,
        evaluations_used: int,
        code_lines: int,
        code_length: int,
        llm_generation_time: float | None = None,
    ) -> tuple[float, str, IterationMetadata]:
        """
        Compute final error, fitness score, feedback message, and metadata object.
        Re-evaluates best_x on the clean underlying problem to calculate an unbiased final error.
        """
        true_optimum = self._problem.true_optimum

        if best_x is not None:
            if len(best_x) != self._problem.dim:
                raise ValueError(
                    f"Returned best_x has dimension {len(best_x)}, expected problem dimension {self._problem.dim}."
                )
            if not self._problem.is_in_bounds(best_x):
                lb_val, ub_val = self._problem.lb[0], self._problem.ub[0]
                raise ValueError(
                    f"Returned best_x {best_x.tolist()} is outside search space bounds [{lb_val}, {ub_val}]. "
                    "Ensure your algorithm clips candidate solutions to domain bounds using problem.clip(x) or np.clip(x, lb, ub)."
                )
            clean_y = float(self._problem._clean_problem(best_x.tolist()))
        else:
            clean_y = algorithm_returned_fitness

        final_error = abs(clean_y - true_optimum)

        feedback = (
            f"The algorithm achieved a final clean error of {final_error:.4f} from the true optimum ({true_optimum:.4f}) "
            f"on BBOB Problem {self._problem.problem_id} (noise model: {self._problem.noise_model}, noise std: {self._problem.noise_std}). "
            "Improve convergence speed and resilience to minimize the final error."
        )

        budget_consumed_pct = (evaluations_used / self._budget * 100) if self._budget > 0 else 0.0
        relative_error = (final_error / abs(true_optimum)) if true_optimum != 0.0 else final_error
        evals_per_second = (evaluations_used / runtime_seconds) if runtime_seconds > 0.0 else 0.0
        error_per_evaluation = (final_error / evaluations_used) if evaluations_used > 0 else None

        metadata = IterationMetadata(
            algorithm_name=algorithm_name,
            execution=Execution(
                timed_out=False,
                runtime_seconds=runtime_seconds,
                llm_generation_time=llm_generation_time,
                evaluations_used=evaluations_used,
                budget_consumed_pct=budget_consumed_pct,
                evals_per_second=evals_per_second,
            ),
            fitness=Fitness(
                raw_fitness=algorithm_returned_fitness,
                final_error=final_error,
                relative_error=relative_error,
                error_per_evaluation=error_per_evaluation,
            ),
            code=Code(
                code_lines=code_lines,
                code_length=code_length,
                code_path=None,
            ),
            error=Error(
                error_type=None,
                error_message=None,
                error_traceback=None,
            ),
            convergence=Convergence.evaluate(final_error, self._convergence_threshold),
        )

        # LLaMEA expects a fitness score where higher is better.
        # We negate the final_error so that an error of 0 is the max (0.0), and larger errors are more negative.
        fitness_score = -final_error

        return fitness_score, feedback, metadata

    def _run_and_score_algorithm(
        self,
        solution: Solution,
        start_time: float,
        code_lines: int,
        code_length: int,
        llm_gen_time: float | None,
    ) -> tuple[float, str, IterationMetadata]:
        """Compile, execute algorithm run with exception handling, and return metrics/feedback."""
        problem_fn = self._problem.get_objective_fn()
        try:
            best_x, algorithm_returned_fitness = self._executor.execute_algorithm(
                code=solution.code,
                name=solution.name,
                dim=self._problem.dim,
                problem=problem_fn,
                budget=self._budget,
            )
            elapsed_time = time.perf_counter() - start_time
            evals_used = self._problem._clean_problem.state.evaluations

            return self._calculate_fitness_and_feedback(
                algorithm_returned_fitness,
                best_x,
                solution.name,
                elapsed_time,
                evals_used,
                code_lines,
                code_length,
                llm_generation_time=llm_gen_time,
            )
        except Exception as error:
            return self._score_failed_algorithm(
                error, solution.name, start_time, code_lines, code_length, llm_gen_time
            )

    def _score_failed_algorithm(
        self,
        error: Exception,
        solution_name: str,
        start_time: float,
        code_lines: int,
        code_length: int,
        llm_gen_time: float | None,
    ) -> tuple[float, str, IterationMetadata]:
        """Handle execution timeout or runtime error, generating failure feedback and metadata."""
        elapsed_time = time.perf_counter() - start_time
        evals_used = self._problem._clean_problem.state.evaluations
        is_timeout = isinstance(error, AlgorithmTimeoutException)

        if is_timeout:
            feedback = (
                f"Execution failed: Your algorithm exceeded the {self._timeout_seconds}-second time limit. "
                "Please optimize your loops and make the code more efficient."
            )
        else:
            feedback = (
                "Execution failed with the following Python error:\n"
                f"{traceback.format_exc()}\n"
                "Please fix the bugs."
            )

        metadata = self._build_error_metadata(
            algorithm_name=solution_name,
            elapsed_time=elapsed_time,
            evals_used=evals_used,
            code_lines=code_lines,
            code_length=code_length,
            llm_gen_time=llm_gen_time,
            is_timeout=is_timeout,
            error=error,
        )

        return float("-inf"), feedback, metadata

    def _build_error_metadata(
        self,
        algorithm_name: str,
        elapsed_time: float,
        evals_used: int,
        code_lines: int,
        code_length: int,
        llm_gen_time: float | None,
        is_timeout: bool,
        error: Exception,
    ) -> IterationMetadata:
        """Construct an IterationMetadata object for failed algorithm executions."""
        budget_consumed_pct = (evals_used / self._budget * 100) if self._budget > 0 else 0.0
        evals_per_second = (evals_used / elapsed_time) if elapsed_time > 0.0 else 0.0
        error_traceback = None if is_timeout else traceback.format_exc()

        return IterationMetadata(
            algorithm_name=algorithm_name,
            execution=Execution(
                timed_out=is_timeout,
                runtime_seconds=elapsed_time,
                llm_generation_time=llm_gen_time,
                evaluations_used=evals_used,
                budget_consumed_pct=budget_consumed_pct,
                evals_per_second=evals_per_second,
            ),
            fitness=Fitness(
                raw_fitness=None,
                final_error=None,
                relative_error=None,
                error_per_evaluation=None,
            ),
            code=Code(
                code_lines=code_lines,
                code_length=code_length,
                code_path=None,
            ),
            error=Error(
                error_type=type(error).__name__,
                error_message=str(error),
                error_traceback=error_traceback,
            ),
            convergence=Convergence.evaluate(None, self._convergence_threshold),
        )

    def _persist_iteration(self, solution: Solution, metadata: IterationMetadata) -> None:
        """Record iteration count, save code file, and persist metadata to database repo."""
        self._current_iteration += 1
        code_path_str: str | None = None

        # 1. Save candidate code file immediately
        if solution.code:
            code_path = self._code_repo.save_code(
                code=solution.code,
                iteration_num=self._current_iteration,
                experiment_id=self._experiment_id,
            )
            code_path_str = str(code_path)

        # Re-create updated, immutable metadata using model_copy
        updated_code = metadata.code.model_copy(update={"code_path": code_path_str})
        final_metadata = metadata.model_copy(
            update={
                "iteration": self._current_iteration,
                "code": updated_code,
            }
        )

        # 2. Append complete iteration metadata to database repo
        self._db_repo.append_iteration(
            experiment_id=self._experiment_id,
            metadata=final_metadata,
        )

    def __call__(self, solution: Solution, explogger: Any | None = None) -> Solution:
        """Execute and score a candidate optimization algorithm solution.

        Args:
            solution: The LLaMEA candidate solution containing its source code and name.
            explogger: Framework-level experiment logger, by default None.

        Returns:
            Solution: The modified solution object populated with fitness scores and feedback.
        """
        code_lines = len(solution.code.splitlines())
        code_length = len(solution.code)
        llm_gen_time = solution.metadata.get("llm_generation_time")

        self._problem.reset()
        start_time = time.perf_counter()

        fitness_score, feedback, metadata = self._run_and_score_algorithm(
            solution, start_time, code_lines, code_length, llm_gen_time
        )

        solution.set_scores(fitness_score, feedback)
        self._persist_iteration(solution, metadata)

        return solution

    def __getstate__(self) -> dict[str, Any]:
        # Exclude unpicklable C++ executor wrapper only.
        # _db_repo and _code_repo are preserved: SQLiteExperimentRepository has its own
        # __getstate__/__setstate__ that safely strips the non-picklable session_factory.
        # Without them, warm-start resumes would have no db_repo and all iteration
        # persistence would silently stop.
        state = self.__dict__.copy()
        state["_executor"] = None
        return state

    def __setstate__(self, state: dict[str, Any]) -> None:
        self.__dict__.update(state)
        # Re-initialize the executor on resume.
        self._executor = AlgorithmExecutor(timeout_seconds=self._timeout_seconds)
        # If _db_repo or _code_repo are None after resume (e.g. from an old pickle),
        # we cannot recover them here — the session must re-attach them after warm_start.
        if self._db_repo is None:
            print(
                "[WARN] Evaluator resumed from pickle with _db_repo=None. "
                "Iteration persistence is DISABLED for this run. "
                "Call evaluator._db_repo = repo to re-attach."
            )
        if self._code_repo is None:
            print(
                "[WARN] Evaluator resumed from pickle with _code_repo=None. "
                "Code file saving is DISABLED for this run."
            )
