"""remove_redundant_index

Revision ID: 03947f576eee
Revises: b3c9776bf537
Create Date: 2026-07-24 17:48:36.577195

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "03947f576eee"
down_revision: Union[str, Sequence[str], None] = "b3c9776bf537"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("iterations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_iterations_experiment"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("iterations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_iterations_experiment"), ["experiment_id"], unique=False
        )

    # ### end Alembic commands ###
