"""remove_iteration_column_from_iterations_table

Revision ID: 1303ffebdc4b
Revises: 676d791ac164
Create Date: 2026-08-02 17:14:53.513908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1303ffebdc4b'
down_revision: Union[str, Sequence[str], None] = '676d791ac164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iterations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_iterations_experiment_iter'))
        batch_op.drop_constraint(batch_op.f('uq_iteration_identity'), type_='unique')
        batch_op.drop_column('iteration')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iterations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iteration', sa.INTEGER(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_iteration_identity'), ['experiment_id', 'iteration'])
        batch_op.create_index(batch_op.f('idx_iterations_experiment_iter'), ['experiment_id', 'iteration'], unique=False)

    # ### end Alembic commands ###
