"""auto_migration

Revision ID: 3a7a275532b2
Revises:
Create Date: 2026-07-11 16:57:16.672757

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3a7a275532b2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experiments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("problem_id", sa.Integer(), nullable=False),
        sa.Column("dim", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("llm_name", sa.String(), nullable=False),
        sa.Column("noise_std", sa.Float(), nullable=True),
        sa.Column("true_optimum", sa.Float(), nullable=True),
        sa.Column("best_iteration", sa.Integer(), nullable=True),
        sa.Column("best_algorithm", sa.String(), nullable=True),
        sa.Column("best_final_error", sa.Float(), nullable=True),
        sa.Column(
            "created_at", sa.String(), server_default=sa.text("(datetime('now'))"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("problem_id", "dim", "mode", "llm_name", name="uq_experiment_run"),
    )
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.create_index(
            "idx_experiments", ["problem_id", "llm_name", "dim", "mode"], unique=False
        )

    op.create_table(
        "iterations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("experiment_id", sa.Integer(), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=True),
        sa.Column("instance_id", sa.Integer(), nullable=True),
        sa.Column("algorithm_name", sa.String(), nullable=True),
        sa.Column("raw_fitness", sa.Float(), nullable=True),
        sa.Column("final_error", sa.Float(), nullable=True),
        sa.Column("true_optimum", sa.Float(), nullable=True),
        sa.Column("noise_std", sa.Float(), nullable=True),
        sa.Column("timed_out", sa.Boolean(), nullable=True),
        sa.Column("runtime_seconds", sa.Float(), nullable=True),
        sa.Column("evaluations_used", sa.Integer(), nullable=True),
        sa.Column("budget_consumed_pct", sa.Float(), nullable=True),
        sa.Column("relative_error", sa.Float(), nullable=True),
        sa.Column("evals_per_second", sa.Float(), nullable=True),
        sa.Column("error_per_evaluation", sa.Float(), nullable=True),
        sa.Column("converged", sa.Boolean(), nullable=True),
        sa.Column("convergence_threshold", sa.Float(), nullable=True),
        sa.Column("code_lines", sa.Integer(), nullable=True),
        sa.Column("code_length", sa.Integer(), nullable=True),
        sa.Column("code_path", sa.String(), nullable=True),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("error_traceback", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["experiment_id"], ["experiments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("iterations", schema=None) as batch_op:
        batch_op.create_index("idx_iterations_experiment", ["experiment_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("iterations", schema=None) as batch_op:
        batch_op.drop_index("idx_iterations_experiment")

    op.drop_table("iterations")
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.drop_index("idx_experiments")

    op.drop_table("experiments")
    # ### end Alembic commands ###
