"""add prompt_strategy column to experiments table

Revision ID: 676d791ac164
Revises: bd9f1ca0f285
Create Date: 2026-07-31 22:08:44.722699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676d791ac164'
down_revision: Union[str, Sequence[str], None] = 'bd9f1ca0f285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_strategy', sa.String(), server_default=sa.text("'baseline'"), nullable=False))
        batch_op.drop_index(batch_op.f('idx_experiments_lookup'))
        batch_op.create_index('idx_experiments_lookup', ['problem_id', 'instance_id', 'llm_name', 'dim', 'mode', 'prompt_strategy'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index('idx_experiments_lookup')
        batch_op.create_index(batch_op.f('idx_experiments_lookup'), ['problem_id', 'instance_id', 'llm_name', 'dim', 'mode'], unique=False)
        batch_op.drop_column('prompt_strategy')

    # ### end Alembic commands ###
