"""add budget and max_iterations columns to experiments table

Revision ID: 702cf0632939
Revises: 1303ffebdc4b
Create Date: 2026-08-04 15:05:31.825666

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "702cf0632939"
down_revision: Union[str, Sequence[str], None] = "1303ffebdc4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("budget", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("max_iterations", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("experiments", schema=None) as batch_op:
        batch_op.drop_column("max_iterations")
        batch_op.drop_column("budget")

    # ### end Alembic commands ###
