"""add_indexes_and_check_constraints

Revision ID: b3c9776bf537
Revises: 3e82d835502a
Create Date: 2026-07-24 17:46:50.071259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c9776bf537'
down_revision: Union[str, Sequence[str], None] = '3e82d835502a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index('idx_experiments_status', ['status'], unique=False)

    with op.batch_alter_table('iterations', schema=None) as batch_op:
        batch_op.create_index('idx_iterations_exp_error', ['experiment_id', 'final_error'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iterations', schema=None) as batch_op:
        batch_op.drop_index('idx_iterations_exp_error')

    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index('idx_experiments_status')

    # ### end Alembic commands ###
