"""add_llm_generation_time

Revision ID: dfff691ff93a
Revises: 3a7a275532b2
Create Date: 2026-07-11 17:23:24.478410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfff691ff93a'
down_revision: Union[str, Sequence[str], None] = '3a7a275532b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iterations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_generation_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('iterations', schema=None) as batch_op:
        batch_op.drop_column('llm_generation_time')

    # ### end Alembic commands ###
