"""LLaMEA Evaluation Adapter (Infrastructure Component).

Executes generated algorithm code in a sandboxed execution harness, scores objective fitness,
enforces timeouts and domain bounds, extracts feedback diagnostics, and persists iteration telemetry.
"""

import math
import re
import time
import traceback
from dataclasses import dataclass, field
from typing import Any

import numpy as np
from llamea import Solution

from evolution.domain.entities import ExperimentSummary
from evolution.domain.interfaces import BaseProblem
from evolution.domain.vos import (
    Code,
    Convergence,
    Error,
    Execution,
    Fitness,
    IterationMetadata,
    ProblemProfile,
)
from evolution.application.synthesis_service import SessionConfig
from evolution.application.interfaces import BaseLogger
from shared.execution import AlgorithmExecutor, AlgorithmTimeoutException
from evolution.infra.logging import SynthesisLogger
from evolution.infra.storage.base import SynthesisRepository
from evolution.infra.storage.code.repository import CodeRepository


_DIVERSITY_INJECTION_MSG = (
    "\n\n[META-FEEDBACK]\n\n"
    "The last several generated algorithms failed to execute correctly.\n\n"
    "Try a substantially different search mechanism rather than making only minor modifications to the previous approach.\n\n"
    "Check the previous implementation for the source of the failure and ensure that the new algorithm respects the objective interface, search bounds, evaluation budget, and numerical constraints."
)


@dataclass
class _ExecutionRunContext:
    """Internal value object encapsulating execution telemetry and candidate output.

    Consolidates data clumps across evaluator scoring and metadata construction methods.
    """

    algorithm_name: str
    runtime_seconds: float
    code_lines: int
    code_length: int
    llm_generation_time: float = 0.0
    evaluations_used: int = 0
    algorithm_returned_fitness: float = 0.0
    best_x: np.ndarray | None = None
    candidate_code: str = ""
    captured_warnings: list[str] = field(default_factory=list)


class Evaluator:
    """
    LLaMEA-compatible evaluator for BBOB optimization problems under noise.

    Workflow:
                 solution.code (generated by LLM)
                                │
                                ▼
                  AlgorithmExecutor.execute_algorithm()
                                │
           ┌────────────────────┴────────────────────────────────────────┐
        Success                                                       Failure
    (returns best_x, raw_y)                               (Timeout, Runtime, Syntax)
           │                                                             │
           ▼                                                             ▼
    1. Validate bounds & dim                             1. Classify failure tier:
    2. Re-evaluate clean optimum:                           • Timeout: -4.0e8
       y_clean = problem.eval_clean(best_x)                 • Runtime: -4.5e8
       error = |y_clean - y*|                               • Failure: -5.0e8
    3. Fitness score = -error                            2. Extract traceback code snippet
    4. Reset consecutive failures                        3. Increment consecutive failures
           │                                                             │
           └────────────────────────────┬────────────────────────────────┘
                                        ▼
                         Stagnation Detection Check:
                 If consecutive_failures >= stagnation_threshold:
                 Inject [META-FEEDBACK] (Force paradigm shift)
                                        │
                                        ▼
                         solution.set_scores(fitness, feedback)
                                        │
                                        ▼
                         Dual Repository Persistence:
                         • Save source code -> CodeRepository
                         • Append telemetry -> SynthesisRepository
                                        │
                                        ▼
                                 Return solution
    """

    FAILURE_FITNESS: float = -5e8
    RUNTIME_FAILURE_FITNESS: float = -4.5e8
    TIMEOUT_FAILURE_FITNESS: float = -4e8

    @classmethod
    def is_failure(cls, score: float) -> bool:
        """Returns True if the score represents any failure tier (crash, runtime, or timeout)."""
        return not math.isfinite(score) or score <= -4e8

    def __init__(
        self,
        problem: BaseProblem,
        db_repo: SynthesisRepository,
        code_repo: CodeRepository,
        experiment_id: int,
        config: SessionConfig,
        initial_iteration: int = 0,
    ) -> None:
        """Initialize the evaluator.

        Args:
            problem: Fully-configured optimization problem instance implementing BaseProblem interface.
            db_repo: ExperimentRepository to persist incremental iteration records.
            code_repo: CodeRepository to persist algorithm source code per iteration.
            experiment_id: Globally unique experiment primary key.
            config: Strongly-typed SessionConfig parameter object.
            initial_iteration: Starting iteration counter (e.g. from warm start), by default 0.
        """
        self._problem = problem
        self._db_repo = db_repo
        self._code_repo = code_repo
        self._config = config
        self._experiment_id = experiment_id
        self._executor = AlgorithmExecutor(timeout_seconds=config.timeout_seconds)
        self._current_iteration = initial_iteration
        self._consecutive_failures = 0
        self._logger = SynthesisLogger()
        self._experiment: ExperimentSummary | None = None

    @property
    def logger(self) -> BaseLogger:
        """Expose the logger used by this evaluator."""
        return self._logger

    @logger.setter
    def logger(self, value: BaseLogger) -> None:
        self._logger = value

    @property
    def executor(self) -> AlgorithmExecutor:
        """Expose the algorithm executor instance."""
        return self._executor

    @executor.setter
    def executor(self, value: AlgorithmExecutor) -> None:
        self._executor = value

    @property
    def experiment(self) -> ExperimentSummary | None:
        """Expose the associated live ExperimentSummary entity."""
        return self._experiment

    @experiment.setter
    def experiment(self, value: ExperimentSummary | None) -> None:
        self._experiment = value

    @property
    def problem_profile(self) -> ProblemProfile:
        """Expose the configured BBOB problem profile."""
        return ProblemProfile(
            problem_id=self._problem.problem_id,
            dim=self._problem.dim,
            noise_std=self._problem.noise_std,
            noise_model=self._problem.noise_model,
            instance_id=self._problem.instance_id,
            true_optimum=self._problem.true_optimum,
        )

    def _resolve_clean_objective(
        self,
        best_x: np.ndarray | None,
        algorithm_returned_fitness: float,
    ) -> float:
        """Validate best_x dimension/bounds if present, re-evaluate clean objective value, and check finite return."""
        if best_x is not None:
            if len(best_x) != self._problem.dim:
                raise ValueError(
                    f"Returned best_x has dimension {len(best_x)}, expected problem dimension {self._problem.dim}."
                )
            if not self._problem.is_in_bounds(best_x):
                lb_val, ub_val = self._problem.lower_bound[0], self._problem.upper_bound[0]
                raise ValueError(
                    f"Returned best_x {best_x.tolist()} is outside search space bounds [{lb_val}, {ub_val}]. "
                    "Ensure your algorithm clips candidate solutions to domain bounds using problem.clip(x) or np.clip(x, lb, ub)."
                )
            clean_y = self._problem.eval_clean(best_x)
        else:
            clean_y = algorithm_returned_fitness

        if not math.isfinite(clean_y):
            raise ValueError(
                f"[INVALID RETURN] Algorithm returned a non-finite value ({clean_y}). "
                "Ensure __call__ returns a valid float — no NaN or inf."
            )

        return clean_y

    def _extract_code_context_from_traceback(self, tb_str: str, candidate_code: str) -> str:
        """Extract lines of generated candidate code referenced in the exception traceback."""
        if not candidate_code or not tb_str:
            return ""

        code_lines = candidate_code.splitlines()
        matches = re.findall(r'File "<string>", line (\d+)', tb_str) or re.findall(
            r'File "[^"]*<string>[^"]*", line (\d+)', tb_str
        )
        if not matches:
            return ""

        context_blocks = []
        seen_lines: set[int] = set()
        for line_str in matches:
            line_num = int(line_str)
            if line_num in seen_lines:
                continue
            seen_lines.add(line_num)

            idx = line_num - 1
            if 0 <= idx < len(code_lines):
                start = max(0, idx - 2)
                end = min(len(code_lines), idx + 3)
                snippet_lines = []
                for i in range(start, end):
                    prefix = "->" if i == idx else "  "
                    snippet_lines.append(f"  {prefix} line {i + 1:3d}: {code_lines[i]}")
                context_blocks.append("\n".join(snippet_lines))

        if not context_blocks:
            return ""

        return "\n---\n".join(context_blocks)

    def _build_success_feedback(
        self,
        final_error: float,
        true_optimum: float,
        captured_warnings: list[str] | None = None,
    ) -> str:
        """Build feedback string for a successful algorithm run."""
        err_str = f"{final_error:.6e}" if abs(final_error) < 1e-4 and final_error != 0 else f"{final_error:.4f}"
        if self._problem.noise_std > 0:
            msg = (
                "[RESULT]\n\n"
                "The generated algorithm executed successfully on a stochastic objective.\n\n"
                f"Final objective error:\n{err_str}\n\n"
                "The result indicates that the current search strategy may not have handled the stochastic evaluations effectively.\n\n"
                "Use the observed result and previous algorithm history to improve the next candidate."
            )
        else:
            msg = (
                "[RESULT]\n\n"
                "The generated algorithm executed successfully.\n\n"
                f"Final objective error:\n{err_str}\n\n"
                "Use this result together with the previous algorithm history when designing the next candidate."
            )

        if captured_warnings:
            warn_str = "\n".join(f"  - {w}" for w in captured_warnings)
            msg += (
                f"\n\nNumPy/Runtime Warnings raised during execution (these may indicate silent bugs):\n"
                f"{warn_str}\n"
                "Check that your code never passes negative values to sqrt, log, or similar functions."
            )
        return msg

    def _build_success_metadata(
        self,
        ctx: _ExecutionRunContext,
        final_error: float,
    ) -> IterationMetadata:
        """Construct IterationMetadata object for successful algorithm executions."""
        true_optimum = self._problem.true_optimum
        budget_consumed_pct = (ctx.evaluations_used / self._config.budget * 100) if self._config.budget > 0 else 0.0
        relative_error = (final_error / abs(true_optimum)) if true_optimum != 0.0 else final_error
        evals_per_second = (ctx.evaluations_used / ctx.runtime_seconds) if ctx.runtime_seconds > 0.0 else 0.0
        error_per_evaluation = (final_error / ctx.evaluations_used) if ctx.evaluations_used > 0 else None

        return IterationMetadata(
            algorithm_name=ctx.algorithm_name,
            execution=Execution(
                timed_out=False,
                runtime_seconds=ctx.runtime_seconds,
                llm_generation_time=ctx.llm_generation_time,
                evaluations_used=ctx.evaluations_used,
                budget_consumed_pct=budget_consumed_pct,
                evals_per_second=evals_per_second,
            ),
            fitness=Fitness(
                raw_fitness=ctx.algorithm_returned_fitness,
                final_error=final_error,
                relative_error=relative_error,
                error_per_evaluation=error_per_evaluation,
            ),
            code=Code(
                code_lines=ctx.code_lines,
                code_length=ctx.code_length,
                code_path=None,
            ),
            error=Error(
                error_type=None,
                error_message=None,
                error_traceback=None,
            ),
            convergence=Convergence.evaluate(final_error, self._config.convergence_threshold),
        )

    def _calculate_fitness_and_feedback(
        self,
        ctx: _ExecutionRunContext,
    ) -> tuple[float, str, IterationMetadata]:
        """Compute final error, fitness score, feedback message, and metadata object.

        Re-evaluates best_x on the clean underlying problem to calculate an unbiased final error.
        """
        true_optimum = self._problem.true_optimum
        clean_y = self._resolve_clean_objective(ctx.best_x, ctx.algorithm_returned_fitness)
        final_error = abs(clean_y - true_optimum)

        feedback = self._build_success_feedback(
            final_error, true_optimum, captured_warnings=ctx.captured_warnings
        )
        metadata = self._build_success_metadata(ctx, final_error)

        # LLaMEA expects a fitness score where higher is better.
        # We negate the final_error so that an error of 0 is the max (0.0), and larger errors are more negative.
        fitness_score = -final_error

        self._logger.generation(
            gen_idx=self._current_iteration + 1,
            total_gens=self._config.iterations,
            algo_name=ctx.algorithm_name or "Candidate",
            error=final_error,
            fitness=fitness_score,
            evals_used=ctx.evaluations_used,
            runtime=ctx.runtime_seconds,
            is_failure=False,
        )

        return fitness_score, feedback, metadata

    def _run_and_score_algorithm(
        self,
        solution: Solution,
        start_time: float,
        code_lines: int,
        code_length: int,
        llm_gen_time: float | None,
    ) -> tuple[float, str, IterationMetadata]:
        """Compile, execute algorithm run with exception handling, and return metrics/feedback."""
        problem_fn = self._problem.get_objective_fn()
        try:
            best_x, algorithm_returned_fitness = self._executor.execute_algorithm(
                code=solution.code,
                name=solution.name,
                dim=self._problem.dim,
                problem=problem_fn,
                budget=self._config.budget,
            )
            elapsed_time = time.perf_counter() - start_time
            evals_used = self._problem.evaluations
            captured = list(getattr(self._executor, "last_captured_warnings", []))

            ctx = _ExecutionRunContext(
                algorithm_name=solution.name,
                runtime_seconds=elapsed_time,
                code_lines=code_lines,
                code_length=code_length,
                llm_generation_time=llm_gen_time,
                evaluations_used=evals_used,
                algorithm_returned_fitness=algorithm_returned_fitness,
                best_x=best_x,
                candidate_code=solution.code,
                captured_warnings=captured,
            )
            return self._calculate_fitness_and_feedback(ctx)
        except Exception as error:
            elapsed_time = time.perf_counter() - start_time
            evals_used = self._problem.evaluations
            captured = list(getattr(self._executor, "last_captured_warnings", []))
            ctx = _ExecutionRunContext(
                algorithm_name=solution.name,
                runtime_seconds=elapsed_time,
                code_lines=code_lines,
                code_length=code_length,
                llm_generation_time=llm_gen_time,
                evaluations_used=evals_used,
                candidate_code=solution.code,
                captured_warnings=captured,
            )
            return self._score_failed_algorithm(ctx, error)

    def _generate_error_feedback(
        self,
        error: Exception,
        is_timeout: bool,
        candidate_code: str = "",
        captured_warnings: list[str] | None = None,
    ) -> str:
        """Generate categorized feedback message based on exception type."""
        if is_timeout:
            msg = (
                "[TIMEOUT]\n\n"
                "The generated algorithm exceeded the execution time limit.\n\n"
                "Reduce unnecessary computation and ensure that the implementation can complete within the available execution time and evaluation budget."
            )
        else:
            tb_str = traceback.format_exc()
            error_str = f"{type(error).__name__}: {error}"
            code_context = self._extract_code_context_from_traceback(tb_str, candidate_code)
            code_section = f"\n\nRelevant code:\n{code_context}" if code_context else ""

            msg = (
                "[RUNTIME ERROR]\n\n"
                "The generated algorithm failed during execution.\n\n"
                f"Error:\n{error_str}"
                f"{code_section}\n\n"
                "Fix the cause of the failure in the next candidate.\n\n"
                "Ensure that:\n"
                "- array shapes and dimensions are valid;\n"
                "- numerical operations are well-defined;\n"
                "- all variables are initialized before use;\n"
                "- the search stays within the provided bounds;\n"
                "- every objective evaluation is counted;\n"
                "- the total number of objective evaluations does not exceed the budget."
            )

        if captured_warnings:
            warn_str = "\n".join(f"  - {w}" for w in captured_warnings)
            msg += (
                f"\n\nNumPy/Runtime Warnings raised during execution (these may indicate silent bugs):\n"
                f"{warn_str}\n"
                "Check that your code never passes negative values to sqrt, log, or similar functions."
            )

        lb_val = self._problem.lower_bound[0] if hasattr(self._problem, "lower_bound") else -5.0
        ub_val = self._problem.upper_bound[0] if hasattr(self._problem, "upper_bound") else 5.0
        msg += f"\n\nProblem context: BBOB-{self._problem.problem_id}, dim={self._problem.dim}, bounds=[{lb_val}, {ub_val}]."

        if self._problem.noise_std > 0:
            msg += (
                "\n\n[NOISY PROBLEM CONTEXT]\n\n"
                "The objective function is stochastic.\n\n"
                "Ensure that optimization decisions are not based on invalid or inconsistently stored objective values.\n\n"
                "Keep any internal statistical estimates separate from the objective value required by the optimizer interface.\n\n"
                "Ensure that every call to problem(x) is counted against the evaluation budget."
            )

        return msg

    def _score_failed_algorithm(
        self,
        ctx: _ExecutionRunContext,
        error: Exception,
    ) -> tuple[float, str, IterationMetadata]:
        """Handle execution timeout or runtime error, generating failure feedback and metadata."""
        is_timeout = isinstance(error, AlgorithmTimeoutException)

        if is_timeout:
            internal_score = self.TIMEOUT_FAILURE_FITNESS
        elif isinstance(
            error,
            (ValueError, TypeError, ZeroDivisionError, OverflowError, FloatingPointError),
        ):
            internal_score = self.RUNTIME_FAILURE_FITNESS
        else:
            internal_score = self.FAILURE_FITNESS

        feedback = self._generate_error_feedback(
            error=error,
            is_timeout=is_timeout,
            candidate_code=ctx.candidate_code,
            captured_warnings=ctx.captured_warnings,
        )

        metadata = self._build_failure_metadata(
            ctx=ctx,
            error=error,
            is_timeout=is_timeout,
        )

        self._logger.generation(
            gen_idx=self._current_iteration + 1,
            total_gens=self._config.iterations,
            algo_name=ctx.algorithm_name or "Candidate",
            error=None,
            fitness=None,
            evals_used=ctx.evaluations_used,
            runtime=ctx.runtime_seconds,
            is_failure=True,
            failure_reason=type(error).__name__,
        )

        return internal_score, feedback, metadata

    def _build_failure_metadata(
        self,
        ctx: _ExecutionRunContext,
        error: Exception,
        is_timeout: bool,
    ) -> IterationMetadata:
        """Construct IterationMetadata for a failed run."""
        error_traceback = None if is_timeout else traceback.format_exc()
        budget_consumed_pct = (ctx.evaluations_used / self._config.budget * 100) if self._config.budget > 0 else 0.0
        evals_per_second = (ctx.evaluations_used / ctx.runtime_seconds) if ctx.runtime_seconds > 0.0 else 0.0

        return IterationMetadata(
            algorithm_name=ctx.algorithm_name,
            execution=Execution(
                timed_out=is_timeout,
                runtime_seconds=ctx.runtime_seconds,
                llm_generation_time=ctx.llm_generation_time,
                evaluations_used=ctx.evaluations_used,
                budget_consumed_pct=budget_consumed_pct,
                evals_per_second=evals_per_second,
            ),
            fitness=Fitness(
                raw_fitness=None,
                final_error=None,
                relative_error=None,
                error_per_evaluation=None,
            ),
            code=Code(
                code_lines=ctx.code_lines,
                code_length=ctx.code_length,
                code_path=None,
            ),
            error=Error(
                error_type=type(error).__name__,
                error_message=str(error),
                error_traceback=error_traceback,
            ),
            convergence=Convergence.evaluate(None, self._config.convergence_threshold),
        )

    def _persist_iteration(self, solution: Solution, metadata: IterationMetadata) -> None:
        """Record iteration count, save code file, and persist metadata to database repo."""
        self._current_iteration += 1
        code_path_str: str | None = None

        # 1. Save candidate code file immediately
        if solution.code:
            code_path = self._code_repo.save_code(
                code=solution.code,
                iteration_num=self._current_iteration,
                experiment_id=self._experiment_id,
            )
            code_path_str = str(code_path)

        # Re-create updated, immutable metadata using model_copy
        updated_code = metadata.code.model_copy(update={"code_path": code_path_str})
        final_metadata = metadata.model_copy(
            update={
                "iteration": self._current_iteration,
                "code": updated_code,
            }
        )

        # 2. Append complete iteration metadata to database repo
        self._db_repo.append_iteration(
            experiment_id=self._experiment_id,
            metadata=final_metadata,
        )

        # 3. Update in-memory domain aggregate
        if self._experiment is not None:
            self._experiment.record_iteration(final_metadata, self._current_iteration)

    def __call__(self, solution: Solution, explogger: Any | None = None) -> Solution:
        """Execute and score a candidate optimization algorithm solution.

        Args:
            solution: The LLaMEA candidate solution containing its source code and name.
            explogger: Framework-level experiment logger, by default None.

        Returns:
            Solution: The modified solution object populated with fitness scores and feedback.
        """
        code_lines = len(solution.code.splitlines())
        code_length = len(solution.code)
        llm_gen_time = solution.metadata.get("llm_generation_time")

        self._problem.reset()
        start_time = time.perf_counter()

        fitness_score, feedback, metadata = self._run_and_score_algorithm(
            solution, start_time, code_lines, code_length, llm_gen_time
        )

        if not math.isfinite(fitness_score):
            fitness_score = self.FAILURE_FITNESS

        if self.is_failure(fitness_score):
            self._consecutive_failures += 1
        else:
            self._consecutive_failures = 0

        diversity_text = ""
        if self._consecutive_failures >= self._config.stagnation_threshold:
            self._logger.stagnation_warning(self._consecutive_failures, self._config.stagnation_threshold)
            diversity_text = _DIVERSITY_INJECTION_MSG.format(n=self._config.stagnation_threshold)
            self._consecutive_failures = 0

        final_feedback = feedback + diversity_text
        solution.set_scores(fitness_score, final_feedback)
        self._persist_iteration(solution, metadata)

        return solution

    def __getstate__(self) -> dict[str, Any]:
        # Exclude unpicklable C++ executor wrapper and logger stream handlers.
        state = self.__dict__.copy()
        state["_executor"] = None
        state["_logger"] = None
        return state

    def __setstate__(self, state: dict[str, Any]) -> None:
        self.__dict__.update(state)
        # Re-initialize the executor and logger on resume.
        self._executor = AlgorithmExecutor(timeout_seconds=self._config.timeout_seconds)
        self._logger = getattr(self, "_logger", None) or SynthesisLogger()
        if self._db_repo is None:
            print(
                "[WARN] Evaluator resumed from pickle with _db_repo=None. "
                "Iteration persistence is DISABLED for this run. "
                "Call evaluator._db_repo = repo to re-attach."
            )
        if self._code_repo is None:
            print(
                "[WARN] Evaluator resumed from pickle with _code_repo=None. "
                "Code file saving is DISABLED for this run."
            )
